#!/bin/sh
#
# wait_for_opening - wait for opening animation to complete or kill it
#
# Ken Steele
# Copyright (c) Chumby Industries, 2007-2008
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA

DONEFILE=/tmp/opening_done

if [ -e /tmp/wait_for_opening ]; then
    while [ 1 ]; do
        if [ -e /tmp/opening_done ]; then
            if [ `cat $DONEFILE` ]; then
                echo "opening animation complete."
                exit
            fi
        fi
        sleep 1
    done
else
	# running standard opening animation
	chumbyflashplayer.x -F15
fi
