#!/bin/sh
#
# $Id: wait_for_usb 24769 2009-11-05 14:18:54Z henry $
# wait_for_usb - wait for the usb subsystem to finish loading before proceeding
#
# Ken Steele / Henry Groover
# Copyright (c) Chumby Industries, 2007-2009
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA

echo -n "waiting for USB subsystem: "

# Get platform-specific definitions
. /etc/hwconfig

i=0
while [ ! -d ${USB_TESTDIR} -a $i -lt 10 ]; do
	sleep 1
    i=`expr $i + 1`
done

s=0
if [ -d /sys/class/scsi_host/host0 ]
then
  while [ $(cat /proc/scsi/scsi | wc -l) -lt 2 -a $s -lt 10 ]; do
    sleep 1
    s=$(expr $s + 1)
  done
else
  echo "No usb drives appear to be mounted.. nothing to wait for..."
fi

wait=$(expr $i + $s)
if [ $i == 10 -o $s == 10 ]; then
	echo "timed out"
else
	echo "loaded in $wait seconds"
fi

